nodeLinker: node-modules

packageExtensions:
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/vue3-vite@*":
    peerDependencies:
      vue: "*"
  eslint-plugin-storybook@*:
    peerDependencies:
      typescript: "*"
  storybook@*:
    peerDependencies:
      "@testing-library/dom": "*"
      react: "*"
      react-dom: "*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
