nodeLinker: node-modules

packageExtensions:
  "storybook@*":
    peerDependencies:
      "@testing-library/dom": "*"
      "react": "*"
      "react-dom": "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/vue3-vite@*":
    peerDependencies:
      "vue": "*"
  "eslint-plugin-storybook@*":
    peerDependencies:
      "typescript": "*"
